services:
  storyvord-frontend-dev:
    container_name: storyvord-frontend-dev
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - storyvord-dev-network

networks:
  storyvord-dev-network:
    name: storyvord-dev-network
    driver: bridge
