services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - storyvord-network

networks:
  storyvord-network:
    name: storyvord-network
    driver: bridge
