name: Azure Static Web Apps CI/CD

on:
  release:
    types: [published]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Adding Node.js setup step
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Pre-Build Setup
        run: corepack enable

      - name: Set Azure API Token
        run: |
          BRANCH_NAME="${{ github.event.release.target_commitish }}"
          echo "Detected branch: $BRANCH_NAME"
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "AZURE_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_PLANT_03ED33600 }}" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "v-02" ]]; then
            echo "AZURE_API_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_RIVER_0BCD86700 }}" >> $GITHUB_ENV
          else
            echo "Unknown branch ($BRANCH_NAME), exiting."
            exit 1
          fi
        shell: bash

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "deploy"

          ###### Repository/Build Configurations - These values can be configured to match your app requirements.
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional, leave empty if not used
          output_location: ".next" # Built app content directory
