name: Azure Static Web Apps CI/CD

on:
  release:
    types: [published]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Adding Node.js setup step
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          PRE_BUILD_COMMAND: corepack enable
          CUSTOM_BUILD_COMMAND: "yarn build" # Ensure the build command uses Yarn 4.3.1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_GROUND_006938C00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          
          ###### Repository/Build Configurations - These values can be configured to match your app requirements.
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional, leave empty if not used
          output_location: ".next" # Built app content directory
          app_build_command: "yarn build"
          ###### End of Repository/Build Configurations ######
